In [1]:
#Name: adarsh Yerneni






import numpy as np

In [1]:
#question1

import numpy as np
#np.random.seed()
random_array = np.random.randint(0,51,size=(3,4)).astype(np.int32)
random_array

array([[42, 25, 43, 34],
       [15, 39, 18, 16],
       [49,  8, 11, 50]], dtype=int32)

In [10]:
np.mean(random_array)

np.float64(18.333333333333332)

In [12]:
np.median(random_array)

np.float64(13.5)

In [13]:
std=np.std(random_array)
formatted_number = "{:.2f}".format(std)
formatted_number

'14.73'

In [17]:
sumofele=0
for rows in random_array:
    for elements in rows:
        sumofele+=elements
        
sumofele

np.float64(220.0)

In [20]:
for rows in random_array:
    summation=np.sum(rows)
    print(summation)


58.0
30.0
132.0


In [23]:
random_array.reshape(2,6)

array([[41.,  0.,  0., 17.,  3.,  9.],
       [10.,  8., 29., 31., 33., 39.]])

In [3]:
#question2
matrix1 = np.random.randint(0, 10,size= (3, 3))
matrix2 = np.random.randint(0, 10, (3, 3))
matrix1


array([[8, 2, 3],
       [3, 0, 5],
       [1, 7, 8]], dtype=int32)

In [25]:
matrix2

array([[7, 5, 0],
       [4, 1, 2],
       [0, 7, 2]], dtype=int32)

In [26]:
matrix1+matrix2

array([[ 8, 10,  8],
       [ 5,  5, 11],
       [ 7, 16,  2]], dtype=int32)

In [27]:
matrix1-matrix2

array([[-6,  0,  8],
       [-3,  3,  7],
       [ 7,  2, -2]], dtype=int32)

In [29]:
dot_product = np.dot(matrix1, matrix2) 
dot_product

array([[27, 66, 26],
       [23, 72, 26],
       [85, 44, 18]], dtype=int32)

In [30]:
np.transpose(matrix1)

array([[1, 1, 7],
       [5, 4, 9],
       [8, 9, 0]], dtype=int32)

In [32]:
np.linalg.det(matrix1)

np.float64(81.99999999999994)

In [34]:
np.linalg.inv(matrix1)

array([[-0.98780488,  0.87804878,  0.15853659],
       [ 0.76829268, -0.68292683, -0.01219512],
       [-0.23170732,  0.31707317, -0.01219512]])